dotenv: .env
dependencies:
  - smartcontractkit/chainlink@2.18.0

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@2.18.0"

networks:
  sepolia:
    ETH_USD_DATA_FEED: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  amoy:
    ETH_USD_DATA_FEED: "0xF0d50568e3A7e8259E16663972b11910F89BD8e7"
    verify: True
  mainnet-fork-dev:
    ETH_USD_DATA_FEED: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  Ganache-local:
    verify: False 